// Code generated by mockery v2.53.2. DO NOT EDIT.

package mocks

import (
	domain "kreditplus/internal/domain"

	mock "github.com/stretchr/testify/mock"
)

// AuthUsecase is an autogenerated mock type for the AuthUsecase type
type AuthUsecase struct {
	mock.Mock
}

// Login provides a mock function with given fields: input
func (_m *AuthUsecase) Login(input domain.LoginInput) (*domain.AuthResponse, error) {
	ret := _m.Called(input)

	if len(ret) == 0 {
		panic("no return value specified for Login")
	}

	var r0 *domain.AuthResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(domain.LoginInput) (*domain.AuthResponse, error)); ok {
		return rf(input)
	}
	if rf, ok := ret.Get(0).(func(domain.LoginInput) *domain.AuthResponse); ok {
		r0 = rf(input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.AuthResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(domain.LoginInput) error); ok {
		r1 = rf(input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RefreshToken provides a mock function with given fields: refreshToken
func (_m *AuthUsecase) RefreshToken(refreshToken string) (*domain.AuthResponse, error) {
	ret := _m.Called(refreshToken)

	if len(ret) == 0 {
		panic("no return value specified for RefreshToken")
	}

	var r0 *domain.AuthResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*domain.AuthResponse, error)); ok {
		return rf(refreshToken)
	}
	if rf, ok := ret.Get(0).(func(string) *domain.AuthResponse); ok {
		r0 = rf(refreshToken)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.AuthResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(refreshToken)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewAuthUsecase creates a new instance of AuthUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAuthUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *AuthUsecase {
	mock := &AuthUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
