// Code generated by mockery v2.53.2. DO NOT EDIT.

package mocks

import (
	domain "kreditplus/internal/domain"

	mock "github.com/stretchr/testify/mock"
)

// LimitUsecase is an autogenerated mock type for the LimitUsecase type
type LimitUsecase struct {
	mock.Mock
}

// CreateLimit provides a mock function with given fields: input
func (_m *LimitUsecase) CreateLimit(input domain.Limit) error {
	ret := _m.Called(input)

	if len(ret) == 0 {
		panic("no return value specified for CreateLimit")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(domain.Limit) error); ok {
		r0 = rf(input)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteLimit provides a mock function with given fields: id
func (_m *LimitUsecase) DeleteLimit(id uint) error {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteLimit")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(uint) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetAllLimits provides a mock function with given fields: limit, offset
func (_m *LimitUsecase) GetAllLimits(limit int, offset int) ([]domain.Limit, error) {
	ret := _m.Called(limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for GetAllLimits")
	}

	var r0 []domain.Limit
	var r1 error
	if rf, ok := ret.Get(0).(func(int, int) ([]domain.Limit, error)); ok {
		return rf(limit, offset)
	}
	if rf, ok := ret.Get(0).(func(int, int) []domain.Limit); ok {
		r0 = rf(limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Limit)
		}
	}

	if rf, ok := ret.Get(1).(func(int, int) error); ok {
		r1 = rf(limit, offset)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetCustomerByNIK provides a mock function with given fields: nik
func (_m *LimitUsecase) GetCustomerByNIK(nik string) (*domain.Customer, error) {
	ret := _m.Called(nik)

	if len(ret) == 0 {
		panic("no return value specified for GetCustomerByNIK")
	}

	var r0 *domain.Customer
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*domain.Customer, error)); ok {
		return rf(nik)
	}
	if rf, ok := ret.Get(0).(func(string) *domain.Customer); ok {
		r0 = rf(nik)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Customer)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(nik)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetLimitByID provides a mock function with given fields: id
func (_m *LimitUsecase) GetLimitByID(id uint) (*domain.Limit, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetLimitByID")
	}

	var r0 *domain.Limit
	var r1 error
	if rf, ok := ret.Get(0).(func(uint) (*domain.Limit, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(uint) *domain.Limit); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Limit)
		}
	}

	if rf, ok := ret.Get(1).(func(uint) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateLimit provides a mock function with given fields: input
func (_m *LimitUsecase) UpdateLimit(input domain.Limit) error {
	ret := _m.Called(input)

	if len(ret) == 0 {
		panic("no return value specified for UpdateLimit")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(domain.Limit) error); ok {
		r0 = rf(input)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewLimitUsecase creates a new instance of LimitUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewLimitUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *LimitUsecase {
	mock := &LimitUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
